spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

# XXL-Job 配置
xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:8100
    executor:
      appname: mall-job-executor
      address:
      ip:
      port: 9999
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30

logging:
  level:
    com.mall: debug
    com.xxl.job: info
