spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_payment?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: payment-producer-group

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  openapi:
    title: 支付服务 API
    description: 模拟支付、退款
    version: 1.0
    group:
      payment:
        group-name: payment
        api-rule: package
        api-rule-resources:
          - com.mall.payment.controller

logging:
  level:
    com.mall: debug

